# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@1
  displayName: "Build using Docker"
  inputs:
    command: Run an image
    imageName: escabe/pvr.jellyfin-build:18.1
    volumes: $(Build.ArtifactStagingDirectory):/output
    runInBackground: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop